name: CI/CD
on: [pull_request, push]

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - name: Build Android
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
          --output $HOME/secrets/secrets.tar secrets.tar.gpg
          tar xvf $HOME/secrets/secrets.tar
          flutter build appbundle
          flutter build apk
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
        # - name: Build iOS
        #   run: |
        #     gpg --quiet --batch --yes --decrypt --passphrase="$SECRET_PASSPHRASE" \
        #     --output $HOME/secrets/secrets.tar secrets.tar.gpg
        #     tar xvf $HOME/secrets/secrets.tar
        #     flutter build ios --no-codesign
        #     cd build/ios/iphoneos
        #     mkdir Payload
        #     cd Payload
        #     ln -s ../Runner.app
        #     cd ..
        #     zip -r app.ipa Payload
        #   env:
        #     SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
      - uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/apk/release/app-release.apk
    # - name: Deploy
    #   if: (github.base_ref == 'master' && github.event_name == 'pull_request')
    #   uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
    #   with:
    #     appId: ${{secrets.FIREBASE_ANDROID_APPID}}
    #     token: ${{secrets.FIREBASE_TOKEN}}
    #     groups: testing
    #     release_notes: "a new version"
    #     file: build/app/outputs/apk/release/app-release.apk
  deploy_app:
    needs: build_and_deploy
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Download articfact for job 1
        uses: actions/download-artifact@v2
        with:
          name: app-release.apk
      - name: Deploy
        if: (github.base_ref == 'master' && github.event_name == 'pull_request')
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testing
          release_notes: "a new version"
          file: /home/runner/work/test/test/app-release.apk
